// home.js

import $ from 'jquery';

export const home = () => {
    const fragment = $(new DocumentFragment());

    const carouselHome = $('<header><div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel"><ol class="carousel-indicators"><li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li><li data-target="#carouselExampleCaptions" data-slide-to="1"></li><li data-target="#carouselExampleCaptions" data-slide-to="2"></li></ol><div class="carousel-inner text-light text-center"><div class="carousel-item home-carousel-img-one active"><div class="carousel-text h-100 p-5 d-flex flex-column justify-content-end justify-content-md-center align-items-center"><div class="hero-shadow"></div><p class="display-3">WYJĄTKOWE MIEJSCE...</p><p class="d-none d-sm-block">Od ponad 30 lat oferujemy to co najlepsze.</p></div></div><div class="carousel-item home-carousel-img-two"><div class="carousel-text h-100 p-5 d-flex flex-column justify-content-end justify-content-md-center align-items-center"><div class="hero-shadow"></div><p class="display-3">LUKSUS DLA KAŻDEGO... </p><p class="d-none d-sm-block">Kompleksowa i profesjonalna pielęgnacja ciała.</p></div></div><div class="carousel-item home-carousel-img-three"><div class="carousel-text h-100 p-5 d-flex flex-column justify-content-end justify-content-md-center align-items-center"><div class="hero-shadow"></div><p class="display-3">ZADBAMY O CIEBIE...</p><p class="d-none d-sm-block">Nasza wysoko wykwalifikowana kadra jest do Państwa dyspozycji.</p></div></div></div><a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev"><span class="carousel-control-prev-icon" aria-hidden="true"></span><span class="sr-only">Previous</span></a><a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next"><span class="carousel-control-next-icon" aria-hidden="true"></span><span class="sr-only">Next</span></a></div></header>');

    const mainSectionOne = $('<main><section class="home-boxes"><div class="container text-center"><div class="row"><div class="col-md-4 home-box mb-5 mb-md-0"><i class="fas fa-hot-tub mb-4"></i><h3>Odnowa biologiczna specjalnie dla Ciebie.</h3></h3><br><p class="m-0">Kompleksowa oferta SPA oraz luksusowe zabiegi pielęgnacyjne pozwalają doświadczyć prawdziwego relaksu oraz skutecznie zregenerować ciało i rozpieścić zmysły.</p></div><div class="col-md-4 home-box mb-5 mb-md-0"><i class="fas fa-laptop-medical mb-4"></i><h3>Oferujemy opiekę medyczną i techniczną.</h3><br><p class="m-0">W naszym ośrodku przez całą dobę jest dostępny lekarz internista oraz sztab wykwalifikowach rehabilitantów. Nasz dział IT również jest do Państwa dyspozycji.</p></div><div class="col-md-4 home-box mb-5 mb-md-0"><i class="fas fa-head-side-mask mb-4"></i><h3>Pandemia podwyższyła nasze standardy.</h3><br><p class="m-0">W obecnym, tak trudnym dla wszystkich czasie, podwyższyliśmy dbałość o bezpieczeństwo naszych gości i pracowników. Jest to w tej chwili naszym priorytetem.</div></section>');

    const mainSectionTwo = $('<section class="home-passion"><div class="hero-shadow"></div><div class="row m-0 h-100 align-items-center text-light"><div class="col"><div class="container p-5"><p class="display-4">Nasza praca<br>to nasza pasja</p><p class="display-5">Zaufaj nam i sprawdź nas...</p></div></div></div></section>')

    const mainSctionThree = $('<section class="home-brand py-5"><p class="display-2 text-center pt-5 px-3">IT SPA</p><div class="container py-5"><div class="row m-0 align-items-center"><div class="col-md-6"><h3>Bazujemy na nowoczesnych zabiegach i kosmetykach</h3><br><p>W dwunastu komfortowych gabinetach w kompleksie IT SPA, wykwalifikowany personel szczególnie dba o przybyłych Gości. Masaże klasyczne i orientalne, rytuały relaksacyjne i upiększające działają jak balsam dla ciała i duszy. „Świat Magicznych Saun” z tepidarium (sauna sucha, parowa, infrasauna), kąpiele w basenie oraz wanny do hydromasażu przynoszą kojący spokój. Naturalne receptury kosmetyków uznanych na świecie marek pobudzają zmysły, dają oczekiwane efekty. IT SPA to profesjonalnie wyposażone gabinety i obsługa na najwyższym poziomie, relaks i odpoczynek.</p></div><div class="col-md-6"><div class="img-fluid stone"></div></div></div></div></section>')

    const jumbotron = $('<div class="container pb-5"><div class="jumbotron text-center"><p class="display-4b">Czekamy na Ciebie</p><hr class="my-4"><p><b>Ośrodek IT SPA</b><br>10-437 Olsztyn, ul. Piękna 18<br>tel. 89 34 56 78, fax 12 34 56<br><a href="mailto: e-mail: biuro@itspa.pl">e-mail: biuro@itspa.pl</a><br><b><a href="#">www.itspa.pl</b></a></p></div><p class="px-4 pt-3">Oferujemy własny dowóz naszych gości z dworców w Olsztynie jaki i z lotniska pasażerskiego w Szymanach. W czasie pobytu w naszym ośrodku istnieje możliwość zorganizowania wycieczek krajoznawczy po Warmii i Mazurach. Posiadamy kilka jachtów zacumowanych na olsztyńskich jeziorach.<br>Serdecznie zapraszamy do przeżycia z nami wielkiej przygody!</p> </div></section>')

    fragment.append(carouselHome).append(mainSectionOne).append (mainSectionTwo).append(mainSctionThree).append(jumbotron);

    return fragment;
};

